---
- name: Install App
  hosts: appsrv
  become: true
  gather_facts: false
  handlers:
  - name: restart go-app
    systemd:
      name: "{{ item }}"
      state: restarted
      daemon_reload: true
    loop: "{{ app_names }}"

  tasks:
  - name: Install Go App Binary
    copy:
      src: files/opt/go-app
      dest: /opt/{{ item }}
      mode: 0755
    loop: "{{ app_names }}"

  - name: Configure Service for Go-App
    notify:
    - restart go-app
    loop: "{{ app_names }}"
    loop_control:
     index_var: my_idx
    blockinfile:
      create: true
      path: /etc/systemd/system/{{ item }}.service
      block: |
        [Unit]
        Description=Go App
        After=network.target

        [Service]
        Environment=APPNAME={{ item }}
        Type=simple
        ExecStart=/opt/{{ item }} {{ db.user }} {{ db.pass }} {{ db.name }} {{ 8080+my_idx }} {{ db.host }}
        Restart=always

        [Install]
        WantedBy=multi-user.target

  - name: Enable Go-App Service
    systemd:
      name: "{{ item }}"
      state: started
      enabled: true
    loop: "{{ app_names }}"
