---
- name: Debug
  hosts: appsrv
  gather_facts: false
  become: true
  tasks:
  - name: Check if service files exist
    stat:
      path: /etc/systemd/system/{{ app_names[0] }}.service
    register: app_svc

  - debug: var=app_svc.stat.exists
