---
- name: Debug
  hosts: localhost
  connection: local
  gather_facts: false
  become: true
  tasks:
  - name: Build /etc/hosts file
    blockinfile:
      create: true
      path: /etc/hosts
      block: |
          {% for host in groups['all'] %}
          {{ hostvars[host]['ansible_host'] }} {{ host }} {{ host }}.example.org
          {% endfor %}
