---
- name: Debug
  hosts: localhost
  connection: local
  gather_facts: false
  become: true
  tasks:
  - lineinfile:
      path: /etc/resolv.conf
      insertbefore: BOF
      line: nameserver {{ hostvars[groups['dns'][0]]['ansible_host'] }}
