---
- name: Gather facts from DNS Server
  hosts: dns

- name: Add DNS Server local
  hosts: localhost
  become: true
  tasks:
  - blockinfile:
      path: /etc/resolv.conf
      insertbefore: BOF
      block: nameserver {{ hostvars[groups['dns'][0]]['ansible_facts'][internal_interface]['ipv4']['address'] }}
