---
nginx_enabled: false
db_enabled: true
lb_enabled: true
dns_enabled: true
registry_enabled: true
docker_enabled: true


app_names:
- "app"
- "osna"

db:
  user: app
  pass: app
  name: app
  host: "{{ hostvars[groups['database'] | first]['ansible_host'] | default('db') }}"

cert_path: /var/tmp

app_crt_key: "{{ cert_path }}/app.key"
app_crt_csr: "{{ cert_path }}/app.csr"
app_crt: "{{ cert_path }}/app.crt"

nginx_conf:
  Debian: "/etc/nginx/sites-enabled/default"
  RedHat: "/etc/nginx/conf.d/default.conf"
nginx_conf_dest: "{{ nginx_conf[ansible_os_family] }}"
nginx_cert_dir: /etc/nginx/tls

haproxy_cert_dir: /etc/haproxy/tls

_pyopenssl_pkg:
  Debian: "python3-openssl"
  RedHat: "python3-pyOpenSSL"
pyopenssl_pkg: "{{ _pyopenssl_pkg[ansible_os_family] }}"

_common_packages:
- vim

common_packages:
- vim
- "{{ pyopenssl_pkg }}"

dns_forwarder: 141.1.1.1

docker_py:
- python3-docker
- python3-distutils
